name: ci-fullstack-workflow

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches: 
      - master

#Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      # Check out the code from the repository.
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up a Node.js environment using the specified node version.
      - name: set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install the dependencies.
      - name: install dependencies
        run: cd backend && npm ci

      # Run the tests.
      - name: run tests
        run: cd backend && npm test

      # Run the linter.
      - name: run the linter
        run: cd backend && npm run lint

      # Send a console message at completion.
      - name: completion message
        run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."

        
